[container_clusters]
us-east-prod-cluster ansible_connection=local ansible_env_KUBECONFIG=/root/.kube/config-east
eu-west-sovereign-cluster ansible_connection=local ansible_env_KUBECONFIG=/root/.kube/config-west

[container_clusters:vars]
ansible_python_interpreter=/usr/bin/python3
